/// Flutter icons Custom_Icons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Custom_Icons
///      fonts:
///       - asset: fonts/Custom_Icons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Custom_Icons {
  Custom_Icons._();

  static const _kFontFam = 'Custom_Icons';


  static const IconData ic_drawer = IconData(0xe800, fontFamily: _kFontFam);
}
