import 'package:flutter/material.dart';

const Color primary = Colors.deepOrange;
const Color red = Colors.red;
const Color white = Colors.white;
const Color black = Colors.black;
Color grey_200 = Colors.grey.shade200;
Color grey_400 = Colors.grey.shade300;
Color white_70 = Colors.white70;
const Color transparent = Colors.transparent;
const Color green = Colors.green;
 Color green_400 = Colors.green[400];
const Color orange = Colors.orange;
const Color blue = Colors.purpleAccent;
const Color amber_accent = Colors.amberAccent;
const Color indgo = Colors.indigo;
const Color purpleAccent = Colors.purple;
Color black_38 = Colors.black38;
Color grey_50 = Colors.grey.shade50;
const Color grey = Colors.grey;
const Color amber = Colors.amber;
 Color pink_50 = Colors.pink[100];
Color pink_10 = Colors.pink[50];
Color orange_50 = Colors.orange[100];
Color orange_300 = Colors.orange[300];
Color blueGrey = Colors.blueGrey;
